### PR TITLE
[PR] Publish feed items as posts

### PR DESCRIPTION
**Pull request by jeremyfelt**
This changes the focus of the plugin quite a bit.

Instead of providing a `/feed-items/` slug with syndicated content, the feed items are only in the dashboard by default. Users can publish these feed items as posts using a checkbox in the submit meta box. This allows a group to sort through syndicated content before deciding what should be on the front page.

screen shot 2016-04-06 at 11 44 43 am
screen shot 2016-04-06 at 11 44 59 am

Once a feed item is published as a post, a link appears to edit that corresponding post. The corresponding post is saved as a draft initially, so the user will need to publish that as well. This behavior can be filtered so that these posts are public by default instead.

Previously, we provided the ability to change the post type of feed items so that they could be published as posts by default. This has been removed. It was used in one theme at WSU for a project that did not get traction.

### CODE REVIEW

**Comment by jeremyfelt** [comment]
@philcable Can you review? The initial documentation for the plugin is here if you want some background - https://web.wsu.edu/wordpress/plugins/wnpa-documentation/ :smile: 

I'm going to work on another PR to improve plugin activation and make sure the cron is working properly.

**Comment by philcable** [comment]
@jeremyfelt Sure thing, I'll check it out soon!

**Comment by philcable** [comment]
@jeremyfelt Just finished combing through this. It all looks good to me and tested out fine 👍 !

**Comment by jeremyfelt** [comment]
@philcable Excellent, thanks!

**Pull request merged**
